version: "2"

services:

  tomcat-container:
    build:
      context: ./tomcat
      dockerfile: Dockerfile
    image: mytomcat-image
    container_name: mytomcat-server
    ports:
      - 9091:8080

  nexus-container:
    build:
      context: ./nexus
      dockerfile: Dockerfile
    image: mynexus-image
    container_name: mynexus-server
    ports:
      - 8082:8081
